config/routes.rb
Rails.application.routes.draw do
  get 'search/busca'
  root 'home#index'
  get 'confirmados', action: 'confirmed', controller: 'home'
  get 'recuperados', action: 'recovered', controller: 'home'
  get 'mortes', action: 'deaths', controller: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_global_summary_service
  def index
    @summary = @summary_service.general
  end

  # def confirmed
  #   @confirmed = @summary_service.confirmed
  # end

  # def recovered
  #   @recovered = @summary_service.recovered
  # end

  # def deaths
  #   @deaths = @summary_service.deaths
  # end

  private
  def set_global_summary_service
    @summary_service = GlobalSummary.new
    
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def busca
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/confirmed.html.erb
<div class="container">
<h1>Casos confirmador</h1>
<table>
  <thead>
    <td>Pais</td>
    <td>Cidade</td>
    <td>Confirmados</td>
    <td>Ultima atualização</td>
  </thead>

  <tbody>
    <% @confirmed.each do |confirmed|%>
      <tr>
        <td><%= confirmed['countryRegion']%></td>
        <td><%= confirmed['provinceState']%></td>
        <td><%= confirmed['confirmed']%></td>
        <td><%= Time.at(confirmed['lastUpdate'].to_i/1000).strftime('%d/%m/%Y %H:%M:%S')%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/home/deaths.html.erb
<div class="container">
<h1>Mortes</h1>
<table>
  <thead>
    <td>Pais</td>
    <td>Cidade</td>
    <td>Confirmados</td>
    <td>Ultima atualização</td>
  </thead>

  <tbody>
    <% @deaths.each do |deaths|%>
      <tr>
        <td><%= deaths['countryRegion']%></td>
        <td><%= deaths['provinceState']%></td>
        <td><%= deaths['confirmed']%></td>
        <td><%= Time.at(deaths['lastUpdate'].to_i/1000).strftime('%d/%m/%Y %H:%M:%S')%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/home/index.html.erb
<div class="container">
<h1>Resultado busca de livros</h1>



<% @summary['items'].each do |item| %>
  <p>Livro: <%= item['volumeInfo']['title']%></p> %>


  <% form_tag do %>
  
  <%= text_field_tag 'busca' %>


  <% end %>


  <%# if item['volumeInfo']['imageLinks']['smallThumbnail']? %>

    <%# thumb = item['volumeInfo']['imageLinks']['smallThumbnail']%>
    <%#=image_tag thumb %>
  <%# end %>
<% end %>
</div>

app/views/home/recovered.html.erb
<div class="container">
<h1>Casos recuperado</h1>
<table>
  <thead>
    <td>Pais</td>
    <td>Cidade</td>
    <td>Confirmados</td>
    <td>Ultima atualização</td>
  </thead>

  <tbody>
    <% @recovered.each do |recovered|%>
      <tr>
        <td><%= recovered['countryRegion']%></td>
        <td><%= recovered['provinceState']%></td>
        <td><%= recovered['confirmed']%></td>
        <td><%= Time.at(recovered['lastUpdate'].to_i/1000).strftime('%d/%m/%Y %H:%M:%S')%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Covid19", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Casos confirmados", confirmados_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "recuperados", recuperados_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "mortes", mortes_path, class:'nav-link' %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoCovid19</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/search/busca.html.erb
<h1>Search#busca</h1>
<p>Find me in app/views/search/busca.html.erb</p>